---
title: "Bee_ground_temp_joining_data"
author: "Liliana_Lay"
date: "2025-07-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Code to attempt joining data sets based on a time in temp_data that most closely matches a time_exited time in bee_data

library(tidyverse)
library(lubridate)

#read in data
bee_data <- # read in cleaned datasets
temp_data <- #read in cleaned datasets

# STEP 1: Prepare temp_data by parsing datetime in temperature data
# temp_data <- temp_data %>%
#   mutate(
#     Time_dt = parse_date_time(paste(Date, Time_fixed), orders = "ymd HM p")
#   ) %>%
#   select(Date, Time_dt, Temperature_F = `Temperature F`)

# STEP 2: Define function to match closest temp on the same date
find_closest_temp <- function(date, exit_time) {
  temps_on_date <- temp_data %>% filter(Date == date)
  
  # If no temps on that date or time is NA, return NA
  if (nrow(temps_on_date) == 0 || is.na(exit_time)) {
    return(NA_real_)
  }
  
  # Compute time differences in seconds
  time_diffs <- abs(difftime(temps_on_date$Time_dt, exit_time, units = "secs"))
  closest_index <- which.min(time_diffs)
  
  # Return temperature safely
  if (length(closest_index) == 0 || is.na(closest_index)) {
    return(NA_real_)
  } else {
    return(as.numeric(temps_on_date$Temperature_F[closest_index]))
  }
}

#also consider doing median temp within range

# STEP 3: Apply function to each row in bee_data and join temperature
bee_data_with_temp <- bee_data %>%
  rowwise() %>%
  mutate(
    Temperature_F = find_closest_temp(Date, Time_Exited_dt)
  ) %>%
  ungroup() %>%
  select(Date, Bee_color, Nest_Number, Time_Entered_dt, Time_Exited_dt, Duration_minutes, Temperature_F)

```


```{r}
#Troubleshooting checks

bee_data %>% 
  select(Date, Time_Exited_dt) %>% 
  head()

temp_data %>% 
  select(Date, Time_dt) %>% 
  head()
```

